#!/usr/bin/env python3
import json,re,shutil,sys
from pathlib import Path
if len(sys.argv)!=3: raise SystemExit("usage: generate.py spec.json mdk")
spec=json.load(open(sys.argv[1],encoding="utf-8")); root=Path(sys.argv[2])
mid=spec["mod_id"].strip(); name=spec.get("mod_name",mid).strip(); desc=spec.get("description","Generated by CircuitMod.").strip(); kind=spec.get("template","basic")
if not re.fullmatch(r"[a-z0-9_]+",mid): raise SystemExit("invalid mod_id")
pkg="com.circuitmod.generated."+mid; pp=Path(*pkg.split(".")); cls="".join(x.capitalize() for x in mid.split("_"))+"Mod"; dollar="$"
src=root/"src/main/java"/pp; res=root/"src/main/resources"; assets=res/"assets"/mid
shutil.rmtree(root/"src/main/java",ignore_errors=True); src.mkdir(parents=True); (res/"META-INF").mkdir(parents=True,exist_ok=True); (assets/"lang").mkdir(parents=True,exist_ok=True); (assets/"models/item").mkdir(parents=True,exist_ok=True)
(root/"gradle.properties").write_text(f"""org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id={mid}
mod_name={name}
mod_license=MIT
mod_version=1.0.0
mod_group_id={pkg}
mod_authors=CircuitMod
mod_description={desc}
""",encoding="utf-8")
build="""plugins {
 id 'eclipse'
 id 'idea'
 id 'maven-publish'
 id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}
version=mod_version
group=mod_group_id
base { archivesName=mod_id }
java.toolchain.languageVersion=JavaLanguageVersion.of(17)
minecraft {
 mappings channel:mapping_channel, version:mapping_version
 copyIdeResources=true
 runs { configureEach { workingDirectory project.file('run'); property 'forge.logging.console.level','debug'; mods { source sourceSets.main } }; client {}; server {} }
}
dependencies { minecraft "net.minecraftforge:forge:" + minecraft_version + "-" + forge_version }
tasks.named('processResources',ProcessResources).configure {
 def p=[minecraft_version:minecraft_version,minecraft_version_range:minecraft_version_range,forge_version:forge_version,forge_version_range:forge_version_range,loader_version_range:loader_version_range,mod_id:mod_id,mod_name:mod_name,mod_license:mod_license,mod_version:mod_version,mod_authors:mod_authors,mod_description:mod_description]
 inputs.properties p
 filesMatching(['META-INF/mods.toml','pack.mcmeta']) { expand p+[project:project] }
}
tasks.named('jar',Jar).configure {
 manifest { attributes(['Specification-Title':mod_id,'Specification-Vendor':mod_authors,'Specification-Version':'1','Implementation-Title':project.name,'Implementation-Version':project.jar.archiveVersion,'Implementation-Vendor':mod_authors]) }
 finalizedBy 'reobfJar'
}
"""
(root/"build.gradle").write_text(build,encoding="utf-8")
(root/"settings.gradle").write_text("pluginManagement { repositories { gradlePluginPortal(); maven { url='https://maven.minecraftforge.net' } } }\nrootProject.name='CircuitModGenerated'\n",encoding="utf-8")
toml='modLoader="javafml"\nloaderVersion="'+dollar+'{loader_version_range}"\nlicense="'+dollar+'{mod_license}"\n\n[[mods]]\nmodId="'+dollar+'{mod_id}"\nversion="'+dollar+'{mod_version}"\ndisplayName="'+dollar+'{mod_name}"\nauthors="'+dollar+'{mod_authors}"\ndescription=\'''\\n'+dollar+'{mod_description}\\n\'''\n\n[[dependencies.'+dollar+'{mod_id}]]\nmodId="forge"\nmandatory=true\nversionRange="'+dollar+'{forge_version_range}"\nordering="NONE"\nside="BOTH"\n\n[[dependencies.'+dollar+'{mod_id}]]\nmodId="minecraft"\nmandatory=true\nversionRange="'+dollar+'{minecraft_version_range}"\nordering="NONE"\nside="BOTH"\n'
(res/"META-INF/mods.toml").write_text(toml,encoding="utf-8")
(res/"pack.mcmeta").write_text('{"pack":{"pack_format":15,"description":"'+dollar+'{mod_name}"}}',encoding="utf-8")
(assets/"lang/en_us.json").write_text(json.dumps({"item."+mid+".circuit_item":name+" Item","entity."+mid+".circuit_mob":name+" Mob"},indent=2),encoding="utf-8")
main=f'''package {pkg};
import net.minecraftforge.fml.common.Mod;
import org.slf4j.Logger;
import com.mojang.logging.LogUtils;
@Mod({cls}.MOD_ID)
public final class {cls} {{
 public static final String MOD_ID="{mid}";
 private static final Logger LOGGER=LogUtils.getLogger();
 public {cls}() {{ LOGGER.info("{name} loaded."); }}
}}
'''
(src/(cls+".java")).write_text(main,encoding="utf-8")
if kind=="item":
 (src/"ModItems.java").write_text(f'''package {pkg};
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.*;
public final class ModItems {{
 public static final DeferredRegister<Item> ITEMS=DeferredRegister.create(ForgeRegistries.ITEMS,{cls}.MOD_ID);
 public static final RegistryObject<Item> CIRCUIT_ITEM=ITEMS.register("circuit_item",()->new Item(new Item.Properties()));
}}
''',encoding="utf-8")
 main=main.replace('LOGGER.info("'+name+' loaded.");','ModItems.ITEMS.register(net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get().getModEventBus()); LOGGER.info("'+name+' loaded.");')
 (src/(cls+".java")).write_text(main,encoding="utf-8")
 (assets/"models/item/circuit_item.json").write_text(json.dumps({"parent":"item/generated","textures":{"layer0":"minecraft:item/diamond"}},indent=2),encoding="utf-8")
if kind=="mob":
 (src/"ModEntities.java").write_text(f'''package {pkg};
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.*;
import net.minecraft.world.entity.monster.Monster;
import net.minecraftforge.registries.*;
public final class ModEntities {{
 public static final DeferredRegister<EntityType<?>> ENTITIES=DeferredRegister.create(ForgeRegistries.ENTITY_TYPES,{cls}.MOD_ID);
 public static final RegistryObject<EntityType<CircuitMob>> CIRCUIT_MOB=ENTITIES.register("circuit_mob",()->EntityType.Builder.of(CircuitMob::new,MobCategory.MONSTER).sized(.6F,1.95F).build("circuit_mob"));
 public static AttributeSupplier.Builder attributes() {{ return Monster.createMonsterAttributes().add(Attributes.MAX_HEALTH,20).add(Attributes.MOVEMENT_SPEED,.25).add(Attributes.ATTACK_DAMAGE,3); }}
}}
''',encoding="utf-8")
 (src/"CircuitMob.java").write_text(f'''package {pkg};
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.monster.Monster;
import net.minecraft.world.level.Level;
public class CircuitMob extends Monster {{ public CircuitMob(EntityType<? extends Monster> t,Level l){{super(t,l);}} }}
''',encoding="utf-8")
 main=main.replace('LOGGER.info("'+name+' loaded.");','ModEntities.ENTITIES.register(net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get().getModEventBus()); LOGGER.info("'+name+' loaded.");')
 (src/(cls+".java")).write_text(main,encoding="utf-8")
print("Generated",name,kind)
